// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfyqzpsdbtnnznflkihl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeXF6cHNkYnRubnpuZmxraWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzM5ODIsImV4cCI6MjA2MzY0OTk4Mn0.OEs9E1xn_Lp9hiLvEq7zmMu7YWE96MUgx9SmGZ19gWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);