
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsqtbciztlqevkegrnfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzcXRiY2l6dGxxZXZrZWdybmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5OTc3MTUsImV4cCI6MjA2MTU3MzcxNX0.2-NLVudXQIKMTnHb-Iu2wrxdt37OVZNgfLDMXGzksLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
